export const umkm = [
  {
    name: "Gorengan Pak Didi",
    image: "/assets/images/umkm/1.webp",
    description: "Deskripsi Gorengan Pak Didi",
    slug: "gorengan-pak-didi",
    category: "makanan",
    location: "Tambun",
    recommended: true,
  },
  {
    name: "Es Teh Poci Bu Rina",
    image: "/assets/images/umkm/2.webp",
    description: "Deskripsi Es Teh Poci Bu Rina",
    slug: "es-teh-poci-bu-rina",
    category: "minuman",
    location: "Dadakitan",
    recommended: false,
  },
  {
    name: "Warung Makan Bu Sari",
    image: "/assets/images/umkm/3.webp",
    description: "Deskripsi Warung Makan Bu Sari",
    slug: "warung-makan-bu-sari",
    category: "makanan",
    location: "Sidoarjo",
    recommended: true,
  },
  {
    name: "Lapak Sayur Segar Pak Udin",
    image: "/assets/images/umkm/4.webp",
    description: "Deskripsi Lapak Sayur Segar Pak Udin",
    slug: "lapak-sayur-segar-pak-udin",
    category: "makanan",
    location: "Lakatan",
    recommended: false,
  },
  {
    name: "Ikan Segar Bang Ijal",
    image: "/assets/images/umkm/5.webp",
    description: "Deskripsi Ikan Segar Bang Ijal",
    slug: "ikan-segar-bang-ijal",
    category: "makanan",
    location: "Sibea",
    recommended: false,
  },
  {
    name: "Kue Tradisional Bu Tuti",
    image: "/assets/images/umkm/6.webp",
    description: "Deskripsi Kue Tradisional Bu Tuti",
    slug: "kue-tradisional-bu-tuti",
    category: "makanan",
    location: "Laulalang",
    recommended: true,
  },
];
